version: '3'
services:
  keycloak_demo:
    image: quay.io/keycloak/keycloak:23.0.4
    command: start-dev
    volumes:
      - /Users/shaniceehioghiren/custom-theme:/opt/keycloak/themes/custom-theme
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak_demo
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8890:8080"
    depends_on:
      postgres_keycloak_demo:
        condition: service_healthy
    networks:
      - keycloak_demo_dev_network
  
  postgres_keycloak_demo:
    image: postgres
    command: postgres -c 'max_connections=200'
    volumes:
      - pgdata_keycloak_demo:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: "exit 0"
    ports:
      - "5436:5432"
    networks:
      - keycloak_demo_dev_network
volumes:
  pgdata_keycloak_demo:
networks:
  keycloak_demo_dev_network:
    driver: bridge

  
